#! /bin/sh

sxhkd &

# cosmetic from https://github.com/Unathi-Skosana/Dotfiles
bspc config normal_border_color   "#2B303B"
bspc config focused_border_color  "#9FA1B3"
bspc config presel_feedback_color "#2B303B"
bspc config normal_sticky_border_color '#2B303B'
bspc config focused_sticky_border_color '#9FA1B3'
bspc config urgent_border_color '#9FA1B3'

bspc config window_gap           20
bspc config top_padding          20
bspc config bottom_padding       10
bspc config left_padding          0
bspc config right_padding         0
bspc config border_width          3
bspc config split_ratio          0.50

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       false
bspc config history_aware_focus     true
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config click_to_focus          false
bspc config center_pseudo_tiled     true

if [ `bspc query -M | wc -l` -eq 2 ]; then
  bspc monitor DP1-1 -d I III V
  bspc monitor DP1-2 -d II IV VI
else
  bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a firefox desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb ~/.Xresources
feh --bg-fill "$HOME/Pictures/Link to home_by_sergey_lesiuk-d6700ip.png"

polybar main &
